INSERT INTO `Ambientacao` (`propostas`) VALUES 
("Lysandra G. Suarez"),
("Lev G. Butler"),
("Megan D. Grimes"),
("Thomas P. Kelly"),
("Hedda V. Thompson"),
("Oprah Kent"),
("Keiko G. Jarvis"),
("Lareina U. Knapp"),
("Asher Boyle"),
("Blossom R. Stein"),
("Joelle G. Simpson"),
("Desiree S. Shepherd"),
("Judith E. Whitney"),
("Gretchen E. Barnes"),
("Alexandra Lindsay"),
("Jessica M. Yates"),
("Briar Y. Harding"),
("Uriah Melendez"),
("Mia Q. Harmon"),
("Xavier Suarez"),
("Xander Strickland"),
("Oliver Stout"),
("Ebony Trevino"),
("Tyrone Sosa"),
("Genevieve J. Clay"),
("Sonia Reid"),
("Stephen Combs"),
("Nevada A. Kline"),
("Orlando B. Garza"),
("Garrison Gallagher"),
("Skyler Rivers"),
("Gay D. Drake"),
("Jennifer Z. Burris"),
("Beatrice Cherry"),
("Cade Cruz"),
("Yael O. Whitley"),
("Levi Macdonald"),
("Quintessa Y. Huff"),
("Germane W. Craig"),
("Yardley Burks");
("Macon Hutchinson"),
("Anika E. Mclean"),
("Dorian C. Blevins"),
("Urielle M. Fisher"),
("Kieran Z. Kane"),
("Belle Kinney"),
("Nigel U. Figueroa"),
("Noel Michael"),
("Aubrey Holcomb"),
("Zeus Aguirre"),
("Arden Duke"),
("Charissa E. Morin"),
("Kylee Melendez"),
("Nicole Cummings"),
("Gwendolyn P. Roth"),
("Lisandra Chan"),
("Kirsten Parker"),
("Nissim Aguirre"),
("Rooney V. Parker"),
("Emi King"),
("Benjamin V. Caldwell"),
("Jaden Dixon"),
("Kelsey D. Noble"),
("Tyrone Z. Ramos"),
("Melanie Farley"),
("Mary Acevedo"),
("Wynter Robles"),
("Stacey Y. Cleveland"),
("Phelan Gould"),
("Rachel Bass");
 ("Jolie Saunders"),
 ("Lael Fleming"),
 ("Odette K. Marquez"),
 ("Yvette Munoz"),
 ("Kristen G. Larsen"),
 ("Barrett Skinner"),
 ("Inga Taylor"),
 ("Jacob Y. Shannon"),
 ("Regan Rasmussen"),
 ("Neve P. Cantu"),
("Stacy Avila"),
("Lucian F. Madden"),(
  "Hammett Turner"),
  ("Kelsey C. Blackburn"),
  ("Patricia E. Greer"),
  ("Victoria Meadows"),
  ("Helen Reid"),
  ("Joshua Y. Brewer"),
  ("Randall Stewart"),
  ("Bruno T. Snider");
("Sydnee P. Winters"),
("Mannix Mcclain"),
("Steven Palmer"),
("Christopher Zimmerman"),
("Susan I. Barrett"),
("Kelsey Wynn"),
("Kenneth P. Washington"),
("Pandora N. Waters"),
("Felix O. Andrews"),
("Tasha Z. Winters");